settings:
  legacy:
    force: true
    interval: 1s
schema:
  - name: proxy
    path: cmd/proxy/
    commands:
      run:
        status: true
    watcher:
      extensions:
        - go
        - yaml
      paths:
        - ../../cmd
        - ../../pkg
        - ../../internal
        - ../../config
      ignored_paths:
        - .git
        - .realize
        - .idea
        - vendor
