---
listener: 8085
verbose: true
routes:
  - "service/1" :
      target: "localhost"
      port: 9001
      path: "/"
  - "service/2" :
      target: "localhost"
      port: 9002
      path: "/"
fallback: "http://localhost:9003"